---
title: A Survey of Accepted Authors in Computer Systems Conferences
preprint: false
author:
  - name: Eitan Frachtenberg
    affiliation: 1
    corresponding: true
    email: eitan@reed.edu
  - name: Noah Koster
    affiliation: 1
    email: kostern@reed.eud
affiliation:
  - code: 1
    address: Department of Computer Science, Reed College
bibliography: ../sysconf.bib
abstract: > 
  Computer Science researchers rely on peer-reviewed conferences to publish their work and to receive feedback. The impact of these peer-reviewed papers on researchers' careers can hardly be overstated. Yet conference organizers can make inconsistent choices for their review process, even in the same subfield. These choices are rarely reviewed critically, and when they are, the emphasis centers on the effects on the technical program, not the authors. In particular, the effects of conference policies on author experience and diversity are still not well understood.


  To help address this knowledge gap, this paper presents a cross-sectional study of 56 conferences from one large subfield of Computer Science, namely computer systems. We introduce a large author survey (n=918), representing 809 unique papers. The goal of this paper is to expose this data and present an initial analysis of its findings. We primarily focus on quantitative comparisons between different survey questions and to external information we collected on author demographics, conference policies, and paper statistics.  

  Another focal point of this study is author diversity. We found poor balance in the gender and geographical distributions of authors, but a more balanced spread across sector, experience, and English-proficiency. For the most part, women and nonnative English speakers exhibit no differences in their experience of the peer-review process, suggesting no specific evidence of bias against these accepted authors. We also found strong support for author rebuttal to reviewers' comments, especially among students and less experienced researchers.
output:
  bookdown::pdf_book:
    base_format: rticles::peerj_article # for using bookdown features like \@ref()
    keep_tex: true
    citation_package: natbib
  rticles::peerj_article: default
---

```{r code = readLines("../load_data.R"), echo = F, message = F}
```


```{r setup-survey, echo=F, message=F, warning=F, cache=F}
library('tidyverse')
library('stringr')
library('kableExtra')

# abstract: "`r readLines('abstract.txt')`"

survey <- read_csv(paste0(toplevel, "/survey/survey-tidy.csv"), col_types = c("-cccffflfffillllfffffnnnnnnn"))
survey$length = factor(survey$length, levels = c("1-2 Paragraphs", "Half a Page", "A Page", "Multiple Pages"))
survey$understanding = factor(survey$understanding, levels = c("Perfectly", "Missed some minor points", "Misunderstood major points", "Probably didn't read it"))
survey$helpfulness = factor(survey$helpfulness, levels = c("Very helpful", "Somewhat helpful", "Not at all"))
survey$fairness = factor(survey$fairness, levels = c("Fair", "Somewhat fair", "Unfair", "Very unfair"))
survey$position = factor(survey$position, levels = c("Government Researcher", "Industry Researcher", "Professor", "Associate Professor", "Assistant Professor", "Postdoctoral Researcher", "Student", "Other"))
survey$months_research = factor(survey$months_research, levels = c("1-3", "4-6", "7-9", "10-12", ">12"))
survey$reviews = factor(survey$reviews, levels = c("0", "1", "2", "3", "4", "5", "6+"))

# Remove responses with irreconcilable conflicts between different authors:
survey <- filter(survey, !response_id %in% c("R_3MbTlW5LmB1KdWV", "R_2pMEwlMUYFK1SYU", "R_2aD0UkJpKRx3E8B", "R_1GWkXIEN7qs4bm6", "R_1ezO6KnFkTiQ7HK", "R_24Nmp0HRk2NWRBT", "R_ABboqawDWihgkMx", "R_0Js4J4xtiVyE6at", "R_2xwRf0e0ekfjozd", "R_wQPB6YJOe7mwHjr"))

raw_survey <- read_csv(paste0(toplevel, "/survey/final_responses.csv"))
all_authors <- read_csv(paste0(toplevel, "/survey/authors-for-survey-without-bounced-emails.csv"))
demographics <- survey %>%
  group_by(response_id) %>%
  summarize(name = first(name), position = first(position), gender = first(gender), mapped_gender = first(mapped_gender), native_english = first(native_english))

demographics <- survey %>%
  group_by(response_id) %>%
  summarize(name = first(name), position = first(position), gender = first(gender), mapped_gender = first(mapped_gender), native_english = first(native_english))

good_affils <- filter(authors, !is.na(sector))
good_positions <- filter(demographics, !is.na(position))
good_genders <- filter(authors, !is.na(gender))

com_table <- data.frame(com = c(sum(good_affils$sector == "COM"), sum(good_positions$position == "Industry Researcher")),
                        notcom = c(sum(good_affils$sector != "COM"), sum(good_positions$position != "Industry Researcher")),
                        row.names = c("email_affiliation", "survey respondents"))

gov_table <- data.frame(gov = c(sum(good_affils$sector == "GOV"), sum(good_positions$position == "Government Researcher")),
                        notcom = c(sum(good_affils$sector != "GOV"), sum(good_positions$position != "Government Researcher")),
                        row.names = c("email_affiliation", "survey respondents"))

gender_table <- data.frame(female = c(sum(good_genders$gender == "F"), sum(demographics$gender == "F", na.rm = T)),
                             male = c(sum(good_genders$gender == "M"), sum(demographics$gender == "M", na.rm = T)),
                        row.names = c("email_affiliation", "survey respondents"))

survey_with_confs <- survey %>%
  mutate(conference = gsub("_\\d\\d\\d", "", paper_id)) %>%
  left_join(all_confs)

english_pcs <- roles %>%
  filter(role == "pc") %>%
  left_join(persons, by = (c("name", "gs_email"))) %>%
  left_join(countries, by = c("country" = "code")) %>%
  filter(!is.na(country)) %>%
  group_by(conf) %>%
  summarize(pct_english = sum(speaks_english) / n()) %>%
  left_join(all_confs, by = c("conf" = "conference")) %>%
  mutate(conf = gsub("_\\d\\d", "", conf))

confs_with_rebut <- survey %>%
  filter(!is.na(rebuttal_helpful)) %>%
  group_by(paper_id, name) %>%
  summarize(rebuttal_helpful = first(rebuttal_helpful)) %>%
  mutate(conference = gsub("_\\d\\d\\d", "", paper_id)) %>%
  left_join(all_confs) %>%
  filter(rebuttal == T) %>%
  group_by(conference) %>%
  mutate(total = n(), happy=sum(rebuttal_helpful == T), unhappy = sum(rebuttal_helpful == F)) %>%
  mutate(ratio = unhappy / total) %>%
  ungroup()

confs_with_subs <- survey %>%
  filter(!is.na(prior_subs)) %>%
  group_by(paper_id) %>%
  summarize(prior_subs = first(prior_subs), rebuttal_helpful = first(rebuttal_helpful)) %>% 
  mutate(conference = gsub("_\\d\\d\\d", "", paper_id)) %>%
  left_join(all_confs)

authors_with_rebut <- survey %>%
  filter(!is.na(rebuttal_helpful)) %>%
  group_by(name, paper_id) %>%
  summarize(rebuttal_helpful = first(rebuttal_helpful), position = first(position), mapped_gender = first(mapped_gender),
            native_english = first(native_english), any_english = first(any_english), prior_subs = first(prior_subs)) %>%
  left_join(authors, by="name")

yes_rebut_help <- filter(authors_with_rebut, rebuttal_helpful == T)
no_rebut_help <- filter(authors_with_rebut, rebuttal_helpful == F)

profs_yes <- nrow(filter(yes_rebut_help, position == "Assistant Professor" | position == "Associate Professor" | position == "Professor"))
students_yes <- nrow(filter(yes_rebut_help, position == "Student"))
women_yes = nrow(filter(yes_rebut_help, mapped_gender == "F"))
men_yes = nrow(filter(yes_rebut_help, mapped_gender == "M"))
english_yes = nrow(filter(yes_rebut_help, native_english == T))
nonenglish_yes = nrow(filter(yes_rebut_help, native_english == F))

profs_no <- nrow(filter(no_rebut_help, position == "Assistant Professor" | position == "Associate Professor" | position == "Professor"))
students_no <- nrow(filter(no_rebut_help, position == "Student"))
women_no = nrow(filter(no_rebut_help, mapped_gender == "F"))
men_no = nrow(filter(no_rebut_help, mapped_gender == "M"))
english_no = nrow(filter(no_rebut_help, native_english == T))
nonenglish_no = nrow(filter(no_rebut_help, native_english == F))
```

