options(Ncpus = parallel::detectCores())
install.packages('devtools')
library('devtools')

devtools::install_version('corrplot', version = '0.92')
devtools::install_version('cowplot', version = '1.1.1')
devtools::install_version('GGally', version = '2.1.2')
devtools::install_version('ggdist', version = '3.3.0')
devtools::install_version('ggrepel', version = '0.9.3')
devtools::install_github('kupietz/kableExtra') #devtools::install_version('kableExtra', version = '1.3.4') Currently buggy
devtools::install_version('lmerTest', version = '3.1-3')
devtools::install_version('MASS', version = '7.3-60')
devtools::install_version('MuMIn', version = '1.47.5')
devtools::install_version('quanteda', version = '3.3.1')
devtools::install_version('quanteda.textplots', version = '0.94.3')
devtools::install_version('quanteda.textstats', version = '0.96.3')
devtools::install_version('readtext', version = '0.90')
devtools::install_version('rgeos', version = '0.6-4')
devtools::install_version('rjson', version = '0.2.21')
devtools::install_version('rnaturalearth', version = '0.3.4')
devtools::install_version('rnaturalearthdata', version = '0.1.0')
devtools::install_version('sf', version = '1.0-14')
devtools::install_version('stringi', version = '1.7.12')
devtools::install_version('tidyverse', version = '2.0.0')
