# Conclusion {-}

This study set out to estimate the ratio of women among systems researchers, and then to explain why it is significantly lower than the rest of CS. We found that women publish at nearly half the rate in systems conferences as they do in the rest of CS, and that this relative underrepresentation is not clearly improved by various conference diversity initiatives such as double-blind reviewing, author position, increased female representation in the program committee or other visible roles, appointment of a diversity chair, and others. It is therefore less likely that the lower ratio of women among systems conference authors is a reflection of bias in the publication process. Instead, we believe that this lower ratio is a reflection of the dismal state of gender diversity in the field.

Our primary explanation to the gender gap in systems from the data and personal accounts is that women's underrepresentation appears to be self-perpetuating. Historical underrepresentation in hardware and engineering disciplines begat a current shortage of female peers, mentors, and role models, which in turns drives emerging women away from the field and leads to future underrepresentation. However, other factors continue to contribute to this underrepresentation, and may require deliberate efforts to break the cycle and make the field more attractive to women.

This and the other explanations proposed in this paper should not necessarily be viewed in contrast to the problems in computer science as a whole. Instead, they can be viewed as a lens that magnifies and brings into focus the causes and effects of lack of diversity in general, which can in turn lead to better outcomes for women and minorities in systems, CS, engineering, and perhaps the technology fields as a whole.
Although the systems is not clearly delineated within computer science, our eclectic conference collection shows that it is a large and heterogeneous field. Since gender representation is so skewed in systems compared to overall computer science, one interesting question would be, what is the actual represenation of women in CS when systems is excluded? Depending on the relative size of Systems in CS, the number could be significantly higher than the oft-quoted 20%, which could lead to diverging diversity efforts between CS as a whole and Systems as a particular problem area.
