# Some packages require R version 3.6 or higher
dependencies <- c(
                  "bindrcpp",
                  "bookdown",
                  "cowplot",
                  "devtools",
                  "GGally",
                  "ggrepel",
                  "jsonlite",
                  "kableExtra",
                  "lme4",
                  "lmerTest",
                  "lubridate",
                  "multidplyr",
                  "NLP",
                  "plotly",
                  "psych",
                  "purrr",
                  "readtext",
                  "reshape2",
                  "readr",
                  "rgeos",
                  "rnaturalearth",
                  "rnaturalearthdata",
                  "rticles",
                  "sf",
                  "slam",
                  "textclean",
                  "textstem",
                  "tidytext",
                  "tidyverse",
                  "wordcloud"
                 )

