---
output:
  pdf_document: default
  html_document: default
---
# Introduction {#sec:intro}

The gender gap in computer science (CS) is a well-known problem with significant societal effects, such as inequality in economic opportunities and an under-supply of engineers in the rapidly growing industry [@mattis07:upstream]. The gender gap among researchers is particularly severe: too few women participate in research, publish about it, and have their research acknowledged for its value [@charman17:championing]. Several studies estimate that only about 20%--30% of the CS research community are women [@cohoon11:cspapers; @holman18:gender; @way16:gender; @zweben18:taulbee]. Despite recent indications that these numbers could be growing, they still remain alarmingly low, and the rate of growth discouragingly slow [@wang19:trends]. Numerous researchers examined the causes and effects of women's low representation in CS, and we review some of these studies in Sec. \@ref(sec:discussion). But CS is a large and diverse discipline with different characteristics in each field. Studies that treat CS as one homogeneous area risk missing some of the gender disparity phenomena that show more acutely in specific fields. In this paper, we focus on one such field, namely, computer systems (or "systems" for short).

Systems is a large research field with numerous applications, used by some of the largest technology companies in the world. Despite its large research output and enormous economic impact, we found no consensus definition what the field consists of, with different organizations and researchers relying on a subjective or intuitive understanding of its scope. Unable to resolve these conflicting definitions, we define systems ourselves for the purpose of our research as the study and engineering of concrete computing systems, which includes research topics such as: operating systems, computer architectures, databases, parallel and distributed computing, and computer networks. This field stands out from other areas of CS in that it emphasizes scientific exploration through system implementation, and in frequently combining engineering, experimentation, simulation, and mathematical rigor.
<!---
As Craig Partridge writes [@partridge98:increase]:

> "The classic systems paper presents an implementation or planned implementation. The implementation can be in software or hardware or both. The implementation's contribution is usually that it either achieves some new function, never before achieved, or it realizes an existing function more efficiently or effectively than previously."
--->

We found that systems also stands out from the rest of CS with ignificantly worse gender representation. There exists anecdotal evidence of this problem for some specific sub-fields of systems [@destefano18:micro]. But to the best of our knowledge, this is the first systematic analysis of gender representation in among systems researchers, analyzing extensive data on systems conferences and their participants. The exposition and open release of this data set constitutes the first contribution of this paper. The main contribution of this paper is to then evaluate women's representaion across multiple factors related to the conferences, the authors, and the field, on order to better understand the causes and effects of this low representation. Throughout the process, we also attempt to independently reproduce several past results on the extensively studied gender gap in CS and technology as a whole, albeit on a completely new data set.


The rest of this paper is organized as follows. In Sec. \@ref(sec:ratio), we explore gender representation across various roles and research sub-fields within these conferences. The following four sections analyze how this representation interacts with factors such as conference policies, author demographics, paper reception, and collaboration patterns, respectively.  Finally, we bring the idiosyncrasies of the systems field back to the larger context of the gender gap in CS as a whole in Sec. \@ref(sec:discussion), which tries to answer the qualitative questions of systems' gender representation in the context of previous work.

## Methodology and Data {-}

We estimate the rate of women's participation in systems research by using the proxy metric of the ratio of women among authors in a set of systems conferences. This approach has been previously tested for different researcher populations [@elsevier17:gender; @lariviere13:bibliometrics]. Typically, these studies look at authors of journal articles, since they represent the highest quality peer-reviewed scientific output for many disciplines. In CS, however, and in particular in its more applied fields such as systems, most scientific output is first published in peer-reviewed conferences [@patterson99:evaluating; @patterson04:health], and then possibly in archival journals (sometimes years later [@vrettas15:conferences]).


The primary data set we analyze is a hand-curated collection of peer-reviewed systems conferences, combined with several external data sources to cross-reference additional demographic information, including gender.^[We recognize that gender is a complex, non-binary identity, but since the focus of this study is on perceived gender, not self-identification, we restrict ourselves to male and female designations.] We chose to focus on a large longitudinal set of conferences from a single publication year (2017), to eliminate variations in time and ensure the relative recency of our results. Since we could find no clear, consensus definition of which topics comprise "systems", our choice of conferences is necessarily subjective, but nevertheless wide enough to cover most well-known conferences in the field. Our set of `r nrow(all_confs)` conferences includes some of the most prestigious systems conferences (based on indirect measurements such as Google Scholar's metrics), as well as several smaller or lower-impact conferences for contrast.^[The complete list of conferences can be found in Appendix A.] All in all, our sample includes `r sum(all_confs$npapers)` peer-reviewed papers with `r nrow(persons)` distinct researchers, mostly authors.  Clearly, not all systems papers in 2017 are in our set, and some papers that are in our set may not necessarily be considered part of systems (for example, if they lean more towards algorithms or theory). But based on our own research experience in systems research, we believe this cross-section of conferences and papers to be representative of the field.

Conferences do not normally collect or share gender information, so we had to infer an author's gender from their forename and affiliation country. Similar studies have typically used online gender-inference services. We initially used genderize.io to infer gender, because it has relatively high accuracy for some countries [@huang19:historical; @karimi16:inferring]. but it appeared to be skewed in that it failed to correctly identify more female names than males, mostly of Asian origin. Instead of relying on this data, we manually checked the gender of `r pct(nrow(verified_gender), nrow(persons), 1)`% of the researchers, for whom we could identify an unambiguous web page with a photo or a pronoun. For `r pct(nrow(inferred_gender), nrow(persons), 1)`% others we used genderize.io's designations if it was at least 70% confident about them, and assigned no gender to the remaining persons. Comparing genderize.io's inferences to our hand-verified data found an accuracy rate of `r pct(nrow(filter(persons, gender=="M"))-461, nrow(filter(persons, gender=="M")), 2)`% for men and `r pct(nrow(filter(persons, gender=="F"))-400, nrow(filter(persons, gender=="F")), 2)`% for women.

Conferences also do not offer information on authors' demographics, but we were able to unambiguously link most authors in our set to a Google Scholar profile with affiliation information and bibliometric statistics. Many authors also provide an email address in the full text of the paper, providing more accurate affiliation information. We have also collected various statistics on each conference, either from its web page or directly from its chairs. Each conference and its papers were hand-annotated with features of interest, such as review policies or paper topics. In addition, we have also collected numerous author opinions and statistics through a survey we ran during 2018. The rest of this paper quantifies women's participation in systems research, and then correlates it with these other variables. 

