# Effect of Conference Policies {#sec:policies}

## Review Policy

## Diversity Initiatives

## Open Access

## Visible Roles

Women are less visible in CS conferences [@klawe95:women, p. 34]

## Conference Reputation

## Historical Perspective

conference policies take time to improve representation (by attracting more women to submit papers or something), so they do help but the effect would not be noticeable from looking at just one year

## Summary 

Contradiction: ISC made active progress in inclusivity since 2016.

Our evidence does not demonstrate an increase in women's authorship as a result of more inclusive conference policies. This may not necessarily indicate a failure of these policies to improve female representation. For example, the female authorship rate may already be representative of the current researcher demographics. But we believe that even if these policies do not immediately improve the objective metrics, they still benefit the subjective experience of diverse authors, which in turn, may prove the field more inviting to future underrepresented researchers. The evalutaion of this effect remains an open research question.
