# Discussion {#sec:discussion}

In this section we use corroborating data and past studies to attempt to answer two of the bigger questions that arise from our data: why is the gender gap  in systems so different across roles, and why is it so different from the rest of CS?

## Role Differences

Women occupy only `r pct(nrow(filter(people_tidy, role == "pc", gender == "F")), nrow(filter(people_tidy, role == "pc", !is.na(gender))), 2)`% of the PC member roles in our data set. But they are even more severely underrerepsented in author roles at `r pct(nrow(filter(people_tidy, role == "author", gender == "F")), nrow(filter(people_tidy, role == "author", !is.na(gender))), 2)`%, unlike many scientific journals, which tend to underrepresent women among editors [\@amrein11:editorial; @mauleon13:assessing; @topaz16:gender]. What is the source of this significant difference, and which ratio better represents the true participation of women in the larger systems research population? We posit that the higher ratios in elected service roles rise from an over-sampling of the available female reserarcher pool, and that the female ratio among peer-reviewed authors is a truer reflection of the gender gap in the field. To motivate this explanation, we present three falsifiable predictions that follow from it.

First, service roles are much fewer in number so a few over-sampled conferences could introduce higher variance with a larger effect on PC ratios. Indeed, Fig. \@ref(fig:women-rep-author-vs-PC) shows a much higher variance and longer tail across conferences in PC female ratios than for authors. There are two conferences with more than 35% female representation in the PC, OOPSLA and ISPASS. Eliding this pair reduces the mean PC female ratio across the remaining conferences to `r without <- filter(people_tidy, !conf %in% c("ISPASS_17", "OOPSLA_17"), !is.na(gender), role == "pc"); pct(nrow(filter(without, gender == "F")), nrow(without), 2)`%.  Conversely, removing the two conferences with the lowest female author ratios (HotI and VEE) only bumps up the mean author female ratio to `r without <- filter(people_tidy, !conf %in% c("HotI_17", "VEE_17"), !is.na(gender), role == "author"); pct(nrow(filter(without, gender == "F")), nrow(without), 2)`%.  Therefore, skewness in distribution pulls the mean female ratios higher among PCs than it pulls it lower among authors, suggesting that the author ratio is closer to the true population mean.

Second, if organizers are indeed over-sampling women for PC roles, we would expect it to show as differences in various statistics for male and female PC members. For example, chairs may have to search deeper in the researcher pool to fill in female roles, leading to lower research standing of the average female PC compared to the males. We find corroboration for this in our data. Fig. \@ref(fig:hindex-distributions) shows that unlike authors, female PCs on average have a lower research standing than men, as measured by their H-index. All other Google Scholar metrics depict a similar picture.

Finally, if women are indeed asked to serve on more PCs than men in relative terms, we would expect to find the same women asked to participate in more PCs than men, as Table \@ref(tab:pct-by-role) would suggest. Our data indeed confirms this prediction, with `r wpc <- filter(pcs, gender == "F") %>% summarize(mean(as_pc + as_pc_chair)); round(wpc, 2)` mean PC memberships per woman to `r mpc <- filter(pcs, gender == "M") %>% summarize(mean(as_pc + as_pc_chair)); round(mpc, 2)` per man (a difference of `r pct(wpc - mpc, mpc, 2)`%). On the other hand, among all authors, women average `r wau <- filter(authors, gender == "F") %>% summarize(mean(as_author)); round(wau, 2)` mean papers published, compared to `r mau <- filter(authors, gender == "M") %>% summarize(mean(as_author)); round(mau, 2)` for men, representing a smaller difference of `r pct(mau - wau, wau)`%. Some studies have suggested a causal link between the two, i.e., that higher participation in service roles reduces women's average scientific production [@cite]. We cannot rule out this explanation, but we note that most authors in our data set (`r pct(nrow(filter(authors, as_pc > 0)), nrow(authors))`%) do not have any PC duties. More importantly, those authors who do serve as PC members tend to be write more papers as well (`r report_cor(cor.test(authors$as_pc, authors$as_author))`). The weak but positive association between number of committees and number of papers suggests that a relative overrepresentation of women in PCs is not commensurate with underrepresentation among authors. Further, the higher prolficity of PC members may be partially explained by higher research experience and standing, as suggested by their higher average H-index (`r report_cor(cor.test(authors$hindex, authors$as_author))`). Therefore some of the lower paper count of female PC members may be explained by their lower average seniority, as opposed to their higher review load.

To summarize, we found indirect evidence that women are selected for services roles in disproprtionate amount to their true rate in the research population. The absence of evidence for female underrepresentation in single-blind reviews also supports to this conclusion. We suggest that this over-sampling reflects an affiromative effort of conference organizers to bolser women's representation in their conferences by inviting qualified women at a higher relative ratio than men. For example, one of the recommendations resulting from the MICRO diversity survey (in the year following our data collection) was to specifically diversify visible conference roles [@destefano18:micro].


## Systems Compared to CS

While some studies place the contemporary percentage of female researchers in CS in the range 20%--30% [@cohoon11:cspapers, @wang19:trends, @zweben18:taulbee], our data suggests that the rate for computer systems is less than half that. What makes this field so much worse than the rest of CS?

Although variance in gender distribution by subfield is an active field of study [@cohoon06:critical, cohoon11:cspapers], some subfields remain poorly understood [@fox06:engineering]. We were able to find no literature that is specific to underrepresentation in Computer Systems. But from conversation with experienced systems researchers and practitioners, it appears that the problem is complex, multi-faceted, and deeply cultural. The following list briefly reviews the relevant literature for computer science and engineering, and extrapolates how these factors could lower women's participation in systems research even further.

1) With its emphasis on performance and implementation, systems is perhaps the closest to other engineering disciplines (and in fact, many systems practitioners graduated in electring or computer engineering programs). And engineering has suffered from a particularly low female participation at the doctoral level [@fox06:engineering]. The overall percentage of women among systems authors in our study, `r pct(nrow(filter(people_tidy, role == "author", gender == "F")), nrow(filter(people_tidy, role == "author", !is.na(gender))))`%, resembles more the 11.6% of engineering jobs in 2002 [@mattis07:upstream] than the 20% of CS [@zweben18:taulbee].

2) Systems is also a field of study that requires an intimate understanding of programming systems and benefits from a longer programming experience. For young undergraduate and graduate students, it is often men who bring more programming experience with them, as boys are more likely than girls to be exposed to and encouraged to pick up programming [@cohoon06:critical; @fisher02:unlocking; @wasburn06:still].

3) Some practitioners also consider the field of computer systems as very competitive, exclusive, or aggressive (perhaps because of its emphasis on performance). As Mary Wyer et al. write: "As a field of study, engineering is rooted in the demands of warfare" [@wyer09:stereotypes]. Such fields may be less appealing to underrepresented populations [@croson09:gender, hurtado10:improving].

4) As our data shows, most systems researchers are men, and therefore most systems labs are primarily male. This cycle where female students, absent role models, mentors, and peers they can easily identify with, end up choosing a different field, which in turn leads to the same shortage of female support network [@bettinger05:faculty; @cohoon06:critical; @klawe95:women; @nelson03:national]. The problem is exacerbated in research groups with a self-perpetuating stereotypical male (or even misogynistic) culture that actively deters women from participating [@fisher02:unlocking; @powell09:women; @wasburn06:still; @wayne09:tightrope].

5) Women are more than twice as likely than men to leave computer science careers [@fisher02:unlocking]. This so-called "leaky pipeline" effect may be even more pronounced in systems, because some of the factors affecting increased attrition are worse in systems, such as isolation by peers and alienation by faculty [@klawe95:women; @nelson03:national]. A higher drop-out rate of women can in turn explain differences in research productivity more than other factors [huang19:historical].

6) Isolation can also lead to less collaboration---necessary in many research venues---but in particular in computer systems, where the implementation of complex systems often requires larger teams. As observed in Sec... ...Different collaboration patterns between gender (and systems is more collaborative? [@fox06:engineering?]). CS average is 2.87 authors per paper [@wang19:trends] but in our set it's `r round(nrow(filter(people_tidy, role=="author")) / sum(all_confs$npapers), 2)`. If much more collaboration is necessary, but not that easy for women, that could be another explanation. And the lack of peers and mentors makes collaboration even harder [@abbate12:recoding, p. 151]

7) Some studies suggest that women are more likely to be attracted to fields with clear societal benefit [@sax19:disciplinary], even within the technology fields [@charles06:degrees; @cohoon11:cspapers; @diekman13:navigating; @margolis00:anatomy]. Although many computer systems directly and indirectly benefit society, it is perceived as a field that primarily focuses on machines, compared to other fields of Computer Science such as human-computer interfaces or application of artificial intelligence. The results reported in Sec. \@ref(subsec:subfield-comparison) appear to confirm that women are less represented in a topic the closer it gets to the machine level.

8) Women publish less in expensive fields?

With so much evidence pointing out to a dearth of support, mentorship, and peers among female systems researchers, it is little wonder that they stood behind the first group for women in computing, "systers" [@abbate12:recoding, p. 167]. This effort has since evolved to encompass women in all of CS and manifests in the annual Grace Hopper Celeberation. ...

## Diferences in productivity

- PC workload, authorship

