---
title: Gender Differences in Collaboration Patterns in Computer Science
preprint: false
author:
  - name: Josh Yamamoto
    affiliation: 1
    corresponding: false
    email: yamamojo@reed.edu
  - name: Alexis Richter
    affiliation: 1
    corresponding: false
    email: ajrichter@reed.edu
  - name: Eitan Frachtenberg
    affiliation: 1
    corresponding: true
    email: eitan@reed.eud
affiliation:
    address: Department of Computer Science, Reed College
bibliography: ../sysconf.bib
abstract: >


output:
  bookdown::pdf_book:
    base_format: rticles::peerj_article
    keep_tex: true
    citation_package: natbib
---

```{r code = readLines("../load_data.R"), echo = F, message = F}
```

```{r setup, echo=F, message=F, warning=F, cache=F}
library('tidyverse')
library('rjson')
library('stringi')

verified_gender_nonsys <- read.csv(paste0(toplevel, "data/nonsys_verified_gender_mapping.csv"), na.strings = "")
inferred_gender_nonsys <- read.csv(paste0(toplevel, "data/nonsys_inferred_gender_mapping.csv"), na.strings = "") %>%
    select(-probability)

# this is the dataframe that we will be joining with the .json nonsys conference files
all_genders <- rbind(inferred_gender_nonsys, verified_gender_nonsys, inferred_gender, verified_gender) %>% 
  distinct(name, .keep_all = T)

# this function breaks an author's reference into their name and optionally their affiliation
author_name <- function(name) {
  m <- str_match(name, "([^\\(]*) \\((.*)\\)$")
  if (is.na(m[,1])) {
    orig <- name
    affil <- NA
  } else {
    orig <- m[,2]
    affil <- m[,3]
  }
  return(c(orig, affil))
}

# this function converts the author's name to title case, removes any titles, and formats their name to be 'lastname, firstname'
normalized_author_name <- function(name) {
  recased <- str_to_title(name)
  recased <- str_replace(recased, "Jr\\.", "") %>%
    str_replace("Sr\\.", "") %>%
    str_replace("Dr\\.", "") %>%
    str_replace("Prof\\.", "")

  names <- author_name(recased)[1]
  names <- stringi::stri_trans_general(names, "Latin-ASCII")
  names <- str_split(names, " ")
  names <- names[[1]]

  if (length(names) == 1) {
    return(names)
  } else {
    last <- tail(names, n = 1)
    rest <- names[1:(length(names) - 1)]

    if (length(rest) == 1) {
      first <- rest
    } else {
      tot <- ""
      for (i in seq_along(rest)) {
        tot <- paste0(tot,' ', rest[i])
      }
      first <- tot
    }

    full <- paste0(last, ", ", first)
    return(full)
  }
}

# This function reads in a .json conference file and for each paper in the conference it extracts the author names, paper id,
# field, and conference id into a data frame. It then normalizes the names using 'normalized_author_name' and moves
# on to the next paper, stacking the new data frame with those that have already been created each time.
# Finally it joins this dataframe with the csv of author names and corresponding genders.

json_to_df <- function(conf_name, gender_mapping) {
  json_fpath <- paste0(toplevel, "data/conf/", conf_name, ".json")
  json <- rjson::fromJSON(file = json_fpath)
  json_sub <- json[['papers']]

  df <- data.frame()
  for (i in seq_along(json_sub)) {
    id <- json_sub[[i]][1]
    authors <- as.data.frame(json_sub[[i]][3])

    authors <- authors %>%
      mutate(paper_id = str_sub(id, -3L, -1L)) %>%
      mutate(conf = json[[1]])

    authors$field <- json[['field']]
    authors$subfield <- json[['subfield']]

    df <- rbind(df, authors)
  }

  names_vector <- df$authors
  names_normed_df <- data.frame()
  for (i in seq_along(names_vector)) {
    new <- as.data.frame(str_replace(normalized_author_name(names_vector[i]), "\\s+", " "))
    names_normed_df <- rbind(names_normed_df, new)
  }

  names(names_normed_df) <- "name"

  if (nrow(df) == nrow(names_normed_df)) {
    df_full <-
      cbind(df, names_normed_df) %>%
      select(-authors)

    df_full %>%
      left_join(gender_mapping, by = "name")

  } else {
    # this should never happen, but just in case we'll check for it
    stop("lengths don't match")
  }
}

# Here we create a vector of the conference names and use the 'map_dfr' function to apply 'json_to_df' to each conference.
nonsys_conf_names <-
  c("AAAI", "ACL", "CHI", "CVPR", "ICML", "ICSE", "MM", "NIPS", "POPL","SIGCSE", "SIGGRAPH", "SODA", "STOC", "WSDM", "WWW", "SIGIR", "KDD", "ICDM", "ITICSE", "FOCS", "TACAS")

nonsys_confs <- nonsys_conf_names %>%
  map_dfr(~json_to_df(.x, all_genders))

```


```{r}
nonsys_confs %>%
  group_by(conf) %>%
  summarise(
    n_papers = n_distinct(paper_id, conf),
    n_na = sum(is.na(gender)),
    n_male = sum(gender == "M", na.rm = T),
    n_female = sum(gender == "F", na.rm = T),
    prop_female = n_female / (n_female + n_male)
    ) %>%
  arrange(desc(prop_female)) %>%
  knitr::kable()

nonsys_confs %>%
  group_by(field) %>%
  summarise(
    n_papers = n_distinct(paper_id, conf),
    n_na = sum(is.na(gender)),
    n_male = sum(gender == "M", na.rm = T),
    n_female = sum(gender == "F", na.rm = T),
    prop_female = n_female / (n_female + n_male)
    ) %>%
  arrange(desc(prop_female)) %>%
  knitr::kable()

nonsys_confs %>%
  group_by(subfield) %>%
  summarise(
    n_papers = n_distinct(paper_id, conf),
    n_na = sum(is.na(gender)),
    n_male = sum(gender == "M", na.rm = T),
    n_female = sum(gender == "F", na.rm = T),
    prop_female = n_female / (n_female + n_male)
    ) %>%
  arrange(desc(prop_female)) %>%
  knitr::kable()
```














